// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZhGlz6pFTPpQpX3ZtVZXCOS8fgKl4FBo',
    appId: '1:629410027017:web:08ebd8e8829463f38bcad8',
    messagingSenderId: '629410027017',
    projectId: 'my-ecommerce-app-123-acb02',
    authDomain: 'my-ecommerce-app-123-acb02.firebaseapp.com',
    storageBucket: 'my-ecommerce-app-123-acb02.firebasestorage.app',
    measurementId: 'G-G831VBF0P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMx3gIO9dlmx7aBCDwtmuNe-Kj-9771g',
    appId: '1:629410027017:android:18fbf24bb80ab6678bcad8',
    messagingSenderId: '629410027017',
    projectId: 'my-ecommerce-app-123-acb02',
    storageBucket: 'my-ecommerce-app-123-acb02.firebasestorage.app',
  );

}